version: '3'

services:
  postgres:
    image: postgres
    container_name: my-postgres
    networks:
      - my-network
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    networks:
      - my-network
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres

networks:
  my-network:
    driver: bridge
